branches:
  - main
  - name: canary-*
    prerelease: true
    channel: canary
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
      writerOpts:
        transform:
          date: false
  - "@semantic-release/npm"
  - "@semantic-release/github"
